name: JSDocs

on: 
  push:
    
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: GIT create new branch
        env:
          CI_COMMIT_AUTHOR: Sophia Yu
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "Syu125@users.noreply.github.com"
          git fetch
      - name: Switch branches and update based on main
        env:
          CI_COMMIT_MESSAGE: Documentation Update
        run: |
          git checkout updateDocumentation
          git merge --strategy-option=theirs main
          echo "[MERGED]"
      - name: install JSDocs
        run: |
          npm install --save-dev jsdoc
          npm version
      - name: update documentation
        run: |
          npm run build --if-present
          npm run generate-docs
      - name: Commit to GIT
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push --set-upstream origin updateDocumentation
        
